export const REQUEST_START = "REQUEST_START";

export const BOOK_DELETED_SUCCESS = "BOOK_DELETED_SUCCESS";
export const BOOK_DELETED_FAIL = "BOOK_DELETED_FAIL";

export const ADDED_BOOK_SUCCESS = "ADDED_BOOK_SUCCESS";
export const ADDED_BOOK_FAIL = "ADDED_BOOK_FAIL";

